package Arboles.UI;

import Arboles.classes.*;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Willy
 */
public class VisualArbol extends javax.swing.JFrame {

    /**
     * Creates new form FormArbol
     */
    private IArbolBusqueda arbol;

    public VisualArbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        radioBtnABB = new javax.swing.JRadioButton();
        radioBtnAVL = new javax.swing.JRadioButton();
        radioBtnAMV = new javax.swing.JRadioButton();
        radioBtnAB = new javax.swing.JRadioButton();
        comboTipoDato = new javax.swing.JComboBox<>();
        btnInstanciar = new javax.swing.JButton();
        labelInstancia = new javax.swing.JLabel();
        textInstancia = new javax.swing.JTextField();
        jLabelVertice = new javax.swing.JLabel();
        textVertice = new javax.swing.JTextField();
        jButtonInsV = new javax.swing.JButton();
        jLabelFuncion = new javax.swing.JLabel();
        textMensaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGrafica = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDel = new javax.swing.JMenu();
        itemIns = new javax.swing.JMenuItem();
        itemDel = new javax.swing.JMenuItem();
        menuRec = new javax.swing.JMenu();
        itemRecNiv = new javax.swing.JMenuItem();
        itemInOrd = new javax.swing.JMenuItem();
        itemPreOrd = new javax.swing.JMenuItem();
        itemPostOrd = new javax.swing.JMenuItem();
        menuMet = new javax.swing.JMenu();
        itemMostrar = new javax.swing.JMenuItem();
        itemAlt = new javax.swing.JMenuItem();
        itemSize = new javax.swing.JMenuItem();
        itemNiv = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(600, 430));
        setSize(new java.awt.Dimension(500, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Arbol"));

        buttonGroup1.add(radioBtnABB);
        radioBtnABB.setSelected(true);
        radioBtnABB.setText("Arbol Binario Busqueda");

        buttonGroup1.add(radioBtnAVL);
        radioBtnAVL.setText("Arbol AVL");

        buttonGroup1.add(radioBtnAMV);
        radioBtnAMV.setText("Arbol M-Vias");

        buttonGroup1.add(radioBtnAB);
        radioBtnAB.setText("Arbol B");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(radioBtnAB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioBtnAMV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioBtnAVL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioBtnABB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radioBtnABB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnAVL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnAMV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnAB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboTipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enteros", "Caracteres", "Strings" }));
        comboTipoDato.setEnabled(false);

        btnInstanciar.setText("Instanciar");
        btnInstanciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstanciarActionPerformed(evt);
            }
        });

        labelInstancia.setText("Instanciado");

        textInstancia.setText("null");

        jLabelVertice.setText("Vertice");

        jButtonInsV.setText("Insertar Varios Vertices");
        jButtonInsV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsVActionPerformed(evt);
            }
        });

        jLabelFuncion.setText("Funcion");

        jLabel1.setText("Arbol Grafico");

        taGrafica.setColumns(20);
        taGrafica.setRows(5);
        jScrollPane1.setViewportView(taGrafica);

        menuDel.setText("Operaciones");

        itemIns.setText("Insertar Vertice");
        itemIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInsActionPerformed(evt);
            }
        });
        menuDel.add(itemIns);

        itemDel.setText("Eliminar Vertice");
        itemDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDelActionPerformed(evt);
            }
        });
        menuDel.add(itemDel);

        jMenuBar1.add(menuDel);

        menuRec.setText("Recorridos");

        itemRecNiv.setText("Por niveles");
        itemRecNiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecNivActionPerformed(evt);
            }
        });
        menuRec.add(itemRecNiv);

        itemInOrd.setText("InOrden");
        itemInOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInOrdActionPerformed(evt);
            }
        });
        menuRec.add(itemInOrd);

        itemPreOrd.setText("PreOrden");
        itemPreOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPreOrdActionPerformed(evt);
            }
        });
        menuRec.add(itemPreOrd);

        itemPostOrd.setText("PostOrden");
        itemPostOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPostOrdActionPerformed(evt);
            }
        });
        menuRec.add(itemPostOrd);

        jMenuBar1.add(menuRec);

        menuMet.setText("Metodos");

        itemMostrar.setText("Mostrar");
        itemMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarActionPerformed(evt);
            }
        });
        menuMet.add(itemMostrar);

        itemAlt.setText("Altura");
        itemAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltActionPerformed(evt);
            }
        });
        menuMet.add(itemAlt);

        itemSize.setText("Size");
        itemSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSizeActionPerformed(evt);
            }
        });
        menuMet.add(itemSize);

        itemNiv.setText("Nivel");
        menuMet.add(itemNiv);

        jMenuBar1.add(menuMet);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textInstancia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnInstanciar)
                    .addComponent(comboTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInstancia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVertice)
                            .addComponent(jLabelFuncion))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textMensaje, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(textVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonInsV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(152, 152, 152))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelVertice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textVertice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInsV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFuncion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(comboTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInstanciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelInstancia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstanciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstanciarActionPerformed
        // TODO add your handling code here:
        String name;
        if (radioBtnABB.isSelected()) {
            arbol = new ArbolBinarioBusqueda<Integer>();
            name = radioBtnABB.getText();
        } else if (radioBtnAVL.isSelected()) {
            arbol = new AVL<Integer>();
            name = radioBtnAVL.getText();
        } else if (radioBtnAMV.isSelected()) {
            int n;
            String m = JOptionPane.showInputDialog(null, "Orden del Arbol");
            n = Integer.parseInt(m);
            try {
                arbol = new ArbolMViasBusqueda<Integer>(n);
            } catch (ExcepcionOrdenInvalido ex) {
                Logger.getLogger(VisualArbol.class.getName()).log(Level.SEVERE, null, ex);
            }
            name = radioBtnAMV.getText();
        } else {
            int n;
            String m = JOptionPane.showInputDialog(null, "Orden del Arbol");
            n = Integer.parseInt(m);
            try {
                arbol = new ArbolB<Integer>(n);
            } catch (ExcepcionOrdenInvalido ex) {
                Logger.getLogger(VisualArbol.class.getName()).log(Level.SEVERE, null, ex);
            }
            name = radioBtnAB.getText();
        }
        textInstancia.setText(name);
        taGrafica.setText(arbol.arbolGrafico());
    }//GEN-LAST:event_btnInstanciarActionPerformed

    private List<Integer> listaDeVertices(String lista) {
        List<Integer> numeros = new LinkedList<>();
        while (lista.length() > 0) {
            int n = lista.length();
            int pos = lista.indexOf(",");
            pos = pos == -1 ? n : pos;
            Integer num = Integer.parseInt(lista.substring(0, pos));
            lista = pos == n ? "" : lista.substring(pos + 1, n);
            numeros.add(num);

        }
        return numeros;
    }

    private void jButtonInsVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsVActionPerformed
        // TODO add your handling code here:
        String vertices
                = JOptionPane.showInputDialog(this, "Vertices", "");
        List<Integer> lista = this.listaDeVertices(vertices);
        for (int i = 0; i < lista.size(); i++) {
            arbol.insertar(lista.get(i));
        }
        taGrafica.setText(arbol.arbolGrafico());
    }//GEN-LAST:event_jButtonInsVActionPerformed

    private void itemMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarActionPerformed
        // TODO add your handling code here:
        taGrafica.setText(arbol.arbolGrafico());
    }//GEN-LAST:event_itemMostrarActionPerformed

    private void itemInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInsActionPerformed
        // TODO add your handling code here:
        String verticeText = this.textVertice.getText();
        Comparable vertice = Integer.parseInt(verticeText);
        boolean ins = arbol.insertar(vertice);
        textMensaje.setText("Vertice(" + verticeText + ") insertado:" + ins);
        itemMostrarActionPerformed(evt);
    }//GEN-LAST:event_itemInsActionPerformed

    private void itemDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDelActionPerformed
        // TODO add your handling code here:
        String verticeText = this.textVertice.getText();
        Comparable vertice = Integer.parseInt(verticeText);
        boolean del = arbol.eliminar(vertice);
        textMensaje.setText("Vertice(" + verticeText + ") eliminado:" + del);
        itemMostrarActionPerformed(evt);
    }//GEN-LAST:event_itemDelActionPerformed

    private void itemAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltActionPerformed
        // TODO add your handling code here:
        textMensaje.setText("Altura del arbol: "+arbol.altura());
    }//GEN-LAST:event_itemAltActionPerformed

    private void itemSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSizeActionPerformed
        // TODO add your handling code here:
        textMensaje.setText("Size del arbol: "+arbol.size());
    }//GEN-LAST:event_itemSizeActionPerformed

    private void itemRecNivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecNivActionPerformed
        // TODO add your handling code here:
        textMensaje.setText("Recorrido por niveles: "+arbol.recorridoPorNiveles());
    }//GEN-LAST:event_itemRecNivActionPerformed

    private void itemInOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInOrdActionPerformed
        // TODO add your handling code here:
        textMensaje.setText("Recorrido por niveles: "+arbol.recorridoEnInOrden());
    }//GEN-LAST:event_itemInOrdActionPerformed

    private void itemPreOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPreOrdActionPerformed
        // TODO add your handling code here:
        textMensaje.setText("Recorrido por niveles: "+arbol.recorridoEnPreOrden());
    }//GEN-LAST:event_itemPreOrdActionPerformed

    private void itemPostOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPostOrdActionPerformed
        // TODO add your handling code here:
        textMensaje.setText("Recorrido por niveles: "+arbol.recorridoEnPostOrden());
    }//GEN-LAST:event_itemPostOrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualArbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstanciar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboTipoDato;
    private javax.swing.JMenuItem itemAlt;
    private javax.swing.JMenuItem itemDel;
    private javax.swing.JMenuItem itemInOrd;
    private javax.swing.JMenuItem itemIns;
    private javax.swing.JMenuItem itemMostrar;
    private javax.swing.JMenuItem itemNiv;
    private javax.swing.JMenuItem itemPostOrd;
    private javax.swing.JMenuItem itemPreOrd;
    private javax.swing.JMenuItem itemRecNiv;
    private javax.swing.JMenuItem itemSize;
    private javax.swing.JButton jButtonInsV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFuncion;
    private javax.swing.JLabel jLabelVertice;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInstancia;
    private javax.swing.JMenu menuDel;
    private javax.swing.JMenu menuMet;
    private javax.swing.JMenu menuRec;
    private javax.swing.JRadioButton radioBtnAB;
    private javax.swing.JRadioButton radioBtnABB;
    private javax.swing.JRadioButton radioBtnAMV;
    private javax.swing.JRadioButton radioBtnAVL;
    private javax.swing.JTextArea taGrafica;
    private javax.swing.JTextField textInstancia;
    private javax.swing.JTextField textMensaje;
    private javax.swing.JTextField textVertice;
    // End of variables declaration//GEN-END:variables
}
